name: Generate ANTLR Regression Reports

on:
  workflow_call:
    inputs:
      patch-branch:
        description: 'The branch to generate the report for'
        required: true
        type: string
      projects-file:
        description: 'project file name for check regression report'
        required: true
        type: string
jobs:
  download-and-commit-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download reports
        uses: actions/download-artifact@v3
        with:
          path: temp-reports

      - name: List reports
        run: |
          echo "LS -R:" && ls -R

      - name: Setup reports to be committed
        id: setup-reports
        run: |
          DATE=$(date +'%Y-%m-%d-T-%H-%M-%S')
          REPORT_DIR="reports/${{ inputs.patch-branch }}/$DATE"
          echo "REPORT_DIR=$REPORT_DIR" >> $GITHUB_OUTPUT
          echo "REPORT_PR_BRANCH_NAME=${{ inputs.patch-branch }}-$DATE" >> $GITHUB_OUTPUT
          mkdir -p $REPORT_DIR
          cp -r temp-reports/* $REPORT_DIR
          rm -rf temp-reports
          echo "LS -R:" && ls -R $REPORT_DIR

      - name: Build body of PR request with links to reports
        id: build-pr-body
        run: |
          echo "REPORT_LINKS<<EOF" >> $GITHUB_OUTPUT
          
          # put projects file name in body
          echo "Projects file: ${{ inputs.projects-file }}" >> $GITHUB_OUTPUT
          
          for f in $(find ${{ steps.setup-reports.outputs.REPORT_DIR }} -maxdepth 2 -type f -name 'index.html'); do
            echo "https://nrmancuso.github.io/$f" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
          done
          
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create PR with reports
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "reports: create reports for ${{ inputs.patch-branch }}"
          title: "reports: create reports for ${{ inputs.patch-branch }}"
          # want to add links to body to copy paste into PR
          body: "${{ steps.build-pr-body.outputs.REPORT_LINKS }}"
          branch: "${{ steps.setup-reports.outputs.REPORT_PR_BRANCH_NAME }}"
          base: "master"
          delete-branch: true
