name: Generate Check Regression Reports

on:
  workflow_call:
    inputs:
      patch-branch:
        description: 'The patch branch to generate the report for'
        required: true
        type: string
      projects-file:
        description: 'The file containing the projects to generate the report for'
        required: true
        type: string
      configs:
        description: 'The config(s) to generate the report with'
        type: string
        required: true

jobs:
  generate_check_regression_report:
    runs-on: ubuntu-latest
    container: checkstyle/jdk-11-groovy-git-mvn:11.0.13__3.0.9__2.25.1__3.6.3
    env:
      MAVEN_OPTS: -Xmx5g
      JAVA_OPTS: -Xmx5g
      CHECKSTYLE_DIRECTORY: checkstyle
      ROOT_DIR: /__w/nrmancuso.github.io/nrmancuso.github.io

      PATCH_BRANCH: ${{ inputs.patch-branch }}
      PROJECTS_FILE: ${{ inputs.projects-file }}

    strategy:
      matrix:
        # use config name with no '.xml' extension
        # generate list with: 'for f in $(find configs -name '*.xml'); do echo " - \"$(echo $f | cut -d '/' -f 2 | cut -d '.' -f 1)\""; done'
        config_name: ${{ fromJson(inputs.configs) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout Checkstyle
        uses: actions/checkout@v3
        with:
          repository: nrmancuso/checkstyle
          path: checkstyle
          fetch-depth: 0

      - name: Checkout Contribution
        uses: actions/checkout@v3
        with:
          repository: checkstyle/contribution
          path: contribution

      - name: Set up local checkstyle repo
        run: |
          cd "${ROOT_DIR}/checkstyle"
          git remote add upstream https://github.com/checkstyle/checkstyle
          git fetch --all
          git checkout master
          git reset --hard upstream/master
          git checkout $PATCH_BRANCH

      - name: Generate report
        env:
          CONFIG_FILE: ${{ matrix.config_name }}.xml
        run: main/scripts/generate-check-regression-report.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config_name }}-report
          path: contribution/checkstyle-tester/reports/diff
          retention-days: 60